# GitLab CI Configuration for Branch Workflow

# Use Node.js 22 image
image: node:22

# Define pipeline stages
stages:
  - test
  - build

# Cache node_modules untuk speed up builds
cache:
  paths:
    - node_modules/

# Variables
variables:
  NODE_ENV: test

# Run tests on merge requests and dev/test branch
test_job:
  stage: test
  before_script:
    - echo "Installing dependencies..."
    - npm ci --cache .npm --prefer-offline
  script:
    - echo "Running tests..."
    - npm test
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
    when: always
  cache:
    paths:
      - .npm/
      - node_modules/
  only:
    - merge_requests
    - dev/test

# Build job (only runs on main branch after merge)
build_job:
  stage: build
  before_script:
    - echo "Installing dependencies..."
    - npm ci --cache .npm --prefer-offline
  script:
    - echo "Building application..."
    - npm run build --if-present || echo "No build script found, skipping..."
  artifacts:
    paths:
      - dist/
      - build/
    expire_in: 1 week
  cache:
    paths:
      - .npm/
      - node_modules/
  only:
    - main
